# Redis
# select image
FROM bearstech/debian:jessie

# user
RUN groupadd -r redis && useradd -r -g redis redis

# install redis
RUN apt-get update && \
    apt-get install -y \
        redis-server \
    && rm -rf /var/lib/apt/lists/*

# data dir
RUN chown -R redis:redis /var/lib/redis

WORKDIR /var/lib/redis

COPY files/redis.conf.jessie /etc/redis/redis.conf

# no root
USER redis

# Expose default redis port
EXPOSE 6379

# node command
CMD ["redis-server", "/etc/redis/redis.conf"]
