---

version: '3'

services:

    server:
        image: bearstech/redis:${DEBIAN_VERSION}

    client:
        image: bearstech/redis:${DEBIAN_VERSION}
        volumes:
            - ./bin/goss:/usr/local/bin/goss
            - ./compose/redis.yaml:/tests/redis.yaml
        working_dir: /tests
        links:
            - server
        environment:
            REDIS_VERSION: ${REDIS_VERSION}
        command: goss -g redis.yaml validate
