---

version: '3'

services:

    server:
        image: bearstech/redis:stretch

    client:
        image: bearstech/redis:stretch
        volumes:
            - ./bin/goss:/usr/local/bin/goss
            - ./compose/redis.yaml:/tests/redis.yaml
        working_dir: /tests
        links:
            - server
        command: goss -g redis.yaml validate
